# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: userdata

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  memorySize: 128

functions:
  studentData:
    handler: handler.userData
    events:
      - http:
          path: user/
          method: get 
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-4beee337
        - sg-e5b0a199
      subnetIds:
        - subnet-778fb33f
        - subnet-806ea2da
        - subnet-bf607cd9